name: MaSuiteChatBridge
main: fi.matiaspaavilainen.masuitechat.MaSuiteChatBridge
version: 1.3.8
author: Masagameplay
softdepend: [GriefPrevention, WorldGuard]
commands:
  mail:
    description: Send mail to player
    aliases: [mailplayer, playermail, mailto]